In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

In [161]:
df = pd.read_csv('Churn_Modelling.csv')
display(df)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [198]:
# 1. Setup & data: Load the file with df = pd.read_csv('Churn_Modelling.csv').
# Display the first 7 rows, then print df.shape and df.columns
display(df.iloc[:7:])
print('shape:', df.shape)
print('columns:', df.columns)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0

shape: (10000, 14)
columns: Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [199]:
# 3. Multi-column sorting: Sort by Geography ascending and Balance descending.
# Show the first 12 rows and explain what the two sort directions mean

df.sort_values(
    by=['Geography', 'Balance'],
    ascending=[True, False]
)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3280,3281,15715622,To Rot,583,France,Female,57,3,238387.56,1,0,1,147964.99,1
1533,1534,15769818,Moore,850,France,Female,37,3,212778.20,1,0,1,69372.88,0
2709,2710,15780212,Mao,592,France,Male,37,4,212692.97,1,0,0,176395.02,0
8702,8703,15690589,Udinesi,541,France,Male,37,9,212314.03,1,0,1,148814.54,0
520,521,15671256,Macartney,850,France,Female,35,1,211774.31,1,1,0,188574.12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9955,9956,15611338,Kashiwagi,714,Spain,Male,29,4,0.00,2,1,1,37605.90,0
9961,9962,15566543,Aldridge,573,Spain,Male,44,9,0.00,2,1,0,107124.17,0
9962,9963,15594612,Flynn,702,Spain,Male,44,9,0.00,1,0,0,59207.41,1
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0

In [200]:
# 6. Replace & map: Create a copy of the DataFrame.
# In the copy, replace Female with F and Male with M using .replace().
# Then solve the same change with .map()

#replace
df_copy = df.copy()
df_copy['Gender'] = df_copy['Gender'].replace(['Female', 'Male'], ['F', 'M'])
display(df_copy)

#map
df_copy = df.copy()
gender_map = {'Female':'F', 'Male':'M'}
df_copy['Gender'] = df_copy['Gender'].map(gender_map)
df_copy

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,F,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,F,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,F,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,F,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,F,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,M,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,M,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,F,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,M,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,F,28,4,130142.79,1,1,0,38190.78,0

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,F,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,F,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,F,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,F,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,F,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,M,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,M,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,F,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,M,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,F,28,4,130142.79,1,1,0,38190.78,0

In [201]:
# 8. sample(): Show 9 random customers using sample(9).
# Then show a 3% random sample using sample(frac=0.03)

display(df.sample(9))
df.sample(frac=0.03)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4995,4996,15583480,Morgan,807,France,Female,36,4,0.00,2,0,1,147007.33,0
4447,4448,15716381,Greece,666,Germany,Female,50,7,109062.28,1,1,1,140136.10,1
3211,3212,15753861,Ballard,686,Germany,Female,27,1,115095.88,2,0,0,78622.46,0
9226,9227,15779913,Davidson,586,France,Male,27,5,130231.80,2,1,1,192427.16,0
1277,1278,15721719,Calabresi,743,France,Male,42,7,77002.20,2,1,1,80428.42,0
8630,8631,15786042,Willmore,706,Germany,Female,44,2,185932.18,2,1,0,65413.41,0
2828,2829,15716449,Fraser,527,Spain,Male,33,9,132168.28,1,0,0,98734.15,0
7779,7780,15699225,Pirozzi,757,France,Male,46,0,0.00,2,1,0,37460.05,0
467,468,15593782,Brookes,816,Germany,Female,38,5,130878.75,3,1,0,71905.77,1

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9612,9613,15794297,McKay,776,France,Male,36,1,0.00,2,1,0,53477.76,0
8851,8852,15590828,Chidimma,782,Germany,Male,42,7,126428.38,1,1,0,39830.10,0
5515,5516,15742534,Faulk,527,Germany,Female,28,2,123802.98,2,1,1,155846.69,0
3146,3147,15730688,Yu,548,France,Female,28,8,116755.50,2,1,1,158585.17,1
9067,9068,15684645,Ajuluchukwu,704,Germany,Male,41,9,62078.21,2,1,0,129050.67,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1367,1368,15627232,Jibunoh,608,Germany,Male,44,7,114203.47,1,1,1,77830.36,1
9959,9960,15677783,Graham,764,Spain,Male,38,4,113607.47,1,1,0,91094.46,0
89,90,15767954,Osborne,635,Germany,Female,28,3,81623.67,2,1,1,156791.36,0
5804,5805,15663933,Jamieson,625,Germany,Female,35,5,86147.46,2,1,0,163440.80,1
8771,8772,15621093,Teng,681,Germany,Male,31,4,97338.19,2,0,0,48226.76,0

In [180]:
# 11. Missing data: Use the DataFrame below and implement the requested cleaning operations

df_missing = pd.DataFrame({
    'A': [None, 2, 3, None, 5, None],
    'B': [10, None, None, 40, 50, None],
    'C': [100, None, 300, 400, None, None]
})
df_missing

     A     B      C
0  NaN  10.0  100.0
1  2.0   NaN    NaN
2  3.0   NaN  300.0
3  NaN  40.0  400.0
4  5.0  50.0    NaN
5  NaN   NaN    NaN

In [173]:
# 11-1. Eliminate any row in the DataFrame that contains at least one NaN value

display(df_missing.dropna())

Empty DataFrame
Columns: [A, B, C]
Index: []

In [175]:
# 11-2. Modify the previous task and eliminate only rows that have NaN values across all columns

display(df_missing.dropna(how='all'))

     A     B      C
0  NaN  10.0  100.0
1  2.0   NaN    NaN
2  3.0   NaN  300.0
3  NaN  40.0  400.0
4  5.0  50.0    NaN

In [176]:
# 11-3. Eliminate rows that have at least one NaN in columns A and C only

display(df_missing.dropna(subset=['A', 'C']))

     A   B      C
2  3.0 NaN  300.0

In [184]:
# 11-4. Replace all NaN values with a specified value of your choice

df_missing['A'] = df_missing['A'].fillna(0)
df_missing['B'] = df_missing['B'].fillna(1)
df_missing['C'] = df_missing['C'].fillna(2)

df_missing

     A          B      C
0  0.0  10.000000  100.0
1  2.0  33.333333    2.0
2  3.0  33.333333  300.0
3  0.0  40.000000  400.0
4  5.0  50.000000    2.0
5  0.0  33.333333    2.0

In [186]:
df_missing = pd.DataFrame({
    'A': [None, 2, 3, None, 5, None],
    'B': [10, None, None, 40, 50, None],
    'C': [100, None, 300, 400, None, None]
})

In [190]:
# 11-5. Replace all NaN values in column B with the mean of the non-NaN values in that column
# note: this command is un-related to the previos one although it gives the same result when you run them one after the other,
#       in order to get netural result you'll nedd to reload the df again (run the cell above)

df_missing['B'] = df_missing['B'].fillna(df_missing['B'].mean())
df_missing

     A          B      C
0  NaN  10.000000  100.0
1  2.0  33.333333    NaN
2  3.0  33.333333  300.0
3  NaN  40.000000  400.0
4  5.0  50.000000    NaN
5  NaN  33.333333    NaN